@accessToken = <YOUR_ACCESS_TOKEN>
@refreshToken = <YOUR_REFRESH_TOKEN>

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~ Chunk ~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Add a chunk to a record
POST http://localhost:3001/chunk/{id}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "startTime": "startTime",
  "endTime": "endTime",
  "audio": "audio"
}

###

# Get chunk by chunkId
GET http://localhost:3001/chunk/{id}/{chunkId}
Authorization: Bearer {{accessToken}}
